name: Django CI

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-buildx-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: ls
        run: |
          RUN_JOB="false"
          echo "::set-env name=RUN_JOB::$RUN_JOB"


      -
        name: Build and push
        id: docker_build
        if: env.RUN_JOB != 'false'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: iradu/django:actions
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}