name: Django CI

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      RUN_JOB2: ${{ steps.ls.outputs.RUN_JOB }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-buildx-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: ls
        id: ls
        run: |
          export RUN_JOB="true"
          export TAG="iradu/django:actions"
          echo "::set-env name=RUN_JOB::$RUN_JOB"
          echo "::set-output name=RUN_JOB::$RUN_JOB"
          echo "::set-output name=TAG::$TAG"
      -
        name: Build and push
        id: docker_build
        if: env.RUN_JOB != 'false'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.TAG }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
